/**
 * Client/session context hints used to enrich session records.
 *
 * This structure provides metadata used when creating or refreshing sessions in
 * the Prisma table Sessions.community_platform_sessions. Properties correspond
 * to columns user_agent, ip, client_platform, client_device, and session_type
 * and are optional inputs that do not contain credentials or tokens.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IClientContext = {
  /**
   * Client-provided user agent string.
   *
   * Maps to Prisma Sessions model column
   * community_platform_sessions.user_agent. Used for device identification
   * and account session management UIs.
   */
  userAgent?: string | undefined;

  /**
   * Last observed client IP address in textual form (IPv4/IPv6).
   *
   * Maps to Prisma Sessions model column community_platform_sessions.ip.
   * Stored as a string for flexibility.
   */
  ip?: string | undefined;

  /**
   * Optional client platform hint (e.g., OS/Browser summary).
   *
   * Maps to Prisma Sessions model column
   * community_platform_sessions.client_platform for usability and security
   * reviews.
   */
  clientPlatform?: string | undefined;

  /**
   * Optional device descriptor (e.g., device model or category).
   *
   * Maps to Prisma Sessions model column
   * community_platform_sessions.client_device captured during session
   * establishment.
   */
  clientDevice?: string | undefined;

  /**
   * Logical classification for the session (e.g., "standard",
   * "admin-console").
   *
   * Maps to Prisma Sessions model column
   * community_platform_sessions.session_type and may influence policy or
   * routing.
   */
  sessionType?: string | undefined;
};
