import { tags } from "typia";

import { IECommunityPlatformAppSettingOrderBy } from "./IECommunityPlatformAppSettingOrderBy";
import { IESortDirection } from "./IESortDirection";

/**
 * Application configuration entry.
 *
 * This schema corresponds to Prisma model community_platform_app_settings. It
 * defines key-value pairs controlling platform behavior, their semantic value
 * types, optional description, active flag, and lifecycle timestamps. Intended
 * for administrative use; clients must not assume specific parsing of the
 * string value without consulting value_type.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformAppSetting = {
  /**
   * Primary key.
   *
   * Prisma: community_platform_app_settings.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Unique configuration key.
   *
   * Prisma: community_platform_app_settings.key. Used programmatically to
   * look up the setting.
   */
  key: string;

  /**
   * Stored value for this setting as string.
   *
   * Prisma: community_platform_app_settings.value. The application layer
   * parses/validates the semantic type.
   */
  value: string;

  /**
   * Semantic type of the value (e.g., "string", "int", "boolean",
   * "duration").
   *
   * Prisma: community_platform_app_settings.value_type.
   */
  value_type: string;

  /**
   * Optional explanation of the setting’s purpose and expected format.
   *
   * Prisma: community_platform_app_settings.description.
   */
  description?: string | null | undefined;

  /**
   * Whether this setting is currently effective.
   *
   * Prisma: community_platform_app_settings.active.
   */
  active: boolean;

  /**
   * Creation timestamp.
   *
   * Prisma: community_platform_app_settings.created_at.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp.
   *
   * Prisma: community_platform_app_settings.updated_at.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp (null when active).
   *
   * Prisma: community_platform_app_settings.deleted_at. Read-only lifecycle
   * marker used to exclude records from standard listings.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityPlatformAppSetting {
  /**
   * Ordering directive for application settings listings.
   *
   * References enumerations for both the column and the direction to ensure
   * strong typing and reusability across endpoints.
   */
  export type ISort = {
    /** Column to order by: key | created_at | updated_at. */
    order_by: IECommunityPlatformAppSettingOrderBy;

    /** Sort direction for the ordered column: asc | desc. */
    order_dir: IESortDirection;
  };

  /**
   * Request parameters for listing/searching app settings (Prisma:
   * community_platform_app_settings). Admin-only usage implied by
   * operations.
   *
   * No sensitive secrets are exposed; actor identity is not accepted in the
   * request body.
   */
  export type IRequest = {
    /** Page number (1-based). */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Items per page. */
    limit?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /**
     * Substring match against configuration key. Prisma:
     * community_platform_app_settings.key.
     */
    key?: (string & tags.MinLength<1>) | null | undefined;

    /**
     * Semantic type filter (e.g., 'string', 'int', 'boolean', 'duration').
     * Prisma: community_platform_app_settings.value_type.
     */
    value_type?: string | null | undefined;

    /**
     * Filter by active flag. Prisma:
     * community_platform_app_settings.active.
     */
    active?: boolean | null | undefined;

    /** Sort key for admin lists. */
    sort_by?: "created_at" | "updated_at" | "key" | null | undefined;

    /** Sort direction; ascending or descending. */
    sort_dir?: "asc" | "desc" | null | undefined;
  };

  /**
   * Application Setting Summary (community_platform_app_settings).
   *
   * This summary type provides a compact, list-ready view of configuration
   * entries defined in the Prisma model community_platform_app_settings. It
   * includes essential fields for administrative list pages and omits
   * potentially sensitive or verbose fields (like value and description) for
   * brevity and safety.
   *
   * All timestamps use ISO 8601 date-time format (UTC).
   */
  export type ISummary = {
    /**
     * Primary key of the setting record
     * (community_platform_app_settings.id).
     *
     * Prisma column type: String @db.Uuid. This is the stable unique
     * identifier for the configuration entry.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Unique configuration key name (community_platform_app_settings.key).
     *
     * Used to retrieve the setting programmatically. Uniqueness is enforced
     * at the database level.
     */
    key: string;

    /**
     * Semantic type of the setting value
     * (community_platform_app_settings.value_type).
     *
     * Examples include: 'string', 'int', 'boolean', 'duration'. Used by
     * admin tools and validators to interpret the stored value.
     */
    value_type: string;

    /**
     * Whether this setting is currently effective
     * (community_platform_app_settings.active).
     *
     * Disabled settings may be retained for historical/audit purposes but
     * not applied by the platform.
     */
    active: boolean;

    /**
     * Last update timestamp (community_platform_app_settings.updated_at) in
     * ISO 8601 date-time format.
     *
     * Useful for admin list sorting and change tracking.
     */
    updated_at: string & tags.Format<"date-time">;
  };
}
