import { tags } from "typia";

/**
 * User profile entity for public presentation based on Prisma model
 * community_platform_user_profiles.
 *
 * Includes display preferences (display_name, avatar_uri, locale, timezone),
 * lifecycle timestamps, and soft deletion marker. This schema is complete with
 * respect to Prisma columns and excludes any authentication secrets.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformUserProfile = {
  /**
   * Primary key of the profile row.
   *
   * Prisma: community_platform_user_profiles.id.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Owner user’s identifier.
   *
   * Prisma: community_platform_user_profiles.community_platform_user_id
   * referencing community_platform_users.id.
   */
  community_platform_user_id: string & tags.Format<"uuid">;

  /**
   * Optional public display name (0–32 chars). When null/empty, clients may
   * use a neutral label (e.g., "Anonymous").
   *
   * Prisma: community_platform_user_profiles.display_name.
   */
  display_name?: (string & tags.MaxLength<32>) | null | undefined;

  /**
   * Optional short biography or introduction text.
   *
   * Prisma: community_platform_user_profiles.bio.
   */
  bio?: string | null | undefined;

  /**
   * Optional avatar image URI.
   *
   * Prisma: community_platform_user_profiles.avatar_uri (stored as VarChar).
   */
  avatar_uri?: (string & tags.Format<"uri">) | null | undefined;

  /**
   * Preferred locale tag (e.g., en-US).
   *
   * Prisma: community_platform_user_profiles.locale.
   */
  locale?: string | null | undefined;

  /**
   * Preferred IANA timezone (e.g., Asia/Seoul).
   *
   * Prisma: community_platform_user_profiles.timezone.
   */
  timezone?: string | null | undefined;

  /**
   * Profile creation timestamp (UTC, ISO 8601).
   *
   * Prisma: community_platform_user_profiles.created_at.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Profile last update timestamp (UTC, ISO 8601).
   *
   * Prisma: community_platform_user_profiles.updated_at.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp for the profile. Null when active.
   *
   * Prisma: community_platform_user_profiles.deleted_at.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
