/**
 * Enumeration for comment vote update requests (PUT operation only).
 *
 * Per business rules, the update operation accepts only UPVOTE or DOWNVOTE.
 * Clearing a vote (state NONE) is handled by the DELETE endpoint and is
 * intentionally excluded here. Maps to
 * Comments.community_platform_comment_votes.value domain {1, -1}.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommentVoteUpdateState = "UPVOTE" | "DOWNVOTE";
