import { tags } from "typia";

/**
 * User identity entity for authorship and permissions context.
 *
 * This schema maps to Prisma model community_platform_users, the central user
 * record referenced by credentials, profiles, sessions, roles, and authored
 * content (posts/comments). It intentionally omits sensitive credential data
 * and focuses on public-safe identity fields required by the platform.
 *
 * Security note: Do not expose password hashes, tokens, or other secrets in
 * user response types. This schema includes only public-safe identity and
 * lifecycle fields.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformUser = {
  /**
   * Primary key of the user.
   *
   * Prisma column: community_platform_users.id
   */
  id: string & tags.Format<"uuid">;

  /**
   * Unique public handle used to identify the account.
   *
   * Prisma column: community_platform_users.username
   */
  username: string & tags.MinLength<1>;

  /**
   * Account status lifecycle label (e.g., active, disabled, pending).
   *
   * Prisma column: community_platform_users.status
   */
  status: string & tags.MinLength<1>;

  /**
   * Timestamp of the last successful login for this account (UTC). Null if
   * never logged in.
   *
   * Prisma column: community_platform_users.last_login_at
   */
  last_login_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Entity creation timestamp (UTC).
   *
   * Prisma column: community_platform_users.created_at
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp (UTC).
   *
   * Prisma column: community_platform_users.updated_at
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp (UTC). Null when active; indicates the record has
   * been removed from active use when set.
   *
   * Prisma column: community_platform_users.deleted_at
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
