import { tags } from "typia";

import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Guest visitor entity reflecting Prisma table
 * community_platform_guestvisitors.
 *
 * This table models anonymous visitors for sessionless interactions, capturing
 * optional device fingerprint, user-agent, IP, and first/last seen timestamps.
 * It does not link to credentials or sessions. Audit logs may reference this id
 * in community_platform_audit_logs.guestvisitor_id.
 *
 * Security: This entity contains no passwords or tokens. It is safe for public
 * read contexts, but still consider privacy for IP and device fingerprint
 * fields.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformGuestVisitor = {
  /**
   * Primary key of the guest visitor (community_platform_guestvisitors.id).
   *
   * This identifier correlates anonymous browsing sessions for analytics and
   * resumable guarded flows.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Optional opaque device/browser fingerprint used to correlate guest
   * activity.
   *
   * Prisma column: community_platform_guestvisitors.device_fingerprint. This
   * value is optional and may be null.
   */
  device_fingerprint?: string | null | undefined;

  /**
   * Observed user-agent string for the guest visitor.
   *
   * Prisma column: community_platform_guestvisitors.user_agent (nullable).
   */
  user_agent?: string | null | undefined;

  /**
   * Observed IP address for the guest visitor.
   *
   * Prisma column: community_platform_guestvisitors.ip (nullable).
   */
  ip?: string | null | undefined;

  /**
   * First observed timestamp for this guest visitor.
   *
   * Prisma column: community_platform_guestvisitors.first_seen_at
   * (timestamptz).
   */
  first_seen_at: string & tags.Format<"date-time">;

  /**
   * Most recent observed timestamp for this guest visitor.
   *
   * Prisma column: community_platform_guestvisitors.last_seen_at
   * (timestamptz).
   */
  last_seen_at: string & tags.Format<"date-time">;
};
export namespace ICommunityPlatformGuestVisitor {
  /**
   * Summary projection of a guest visitor for embedding within authorization
   * responses.
   *
   * This summary excludes potentially sensitive networking hints (IP and
   * user-agent) and focuses on stable identification and recency timestamps.
   */
  export type ISummary = {
    /**
     * Guest visitor id (UUID).
     *
     * Prisma: community_platform_guestvisitors.id.
     */
    id: string & tags.Format<"uuid">;

    /**
     * First observed timestamp for this guest visitor.
     *
     * Prisma: community_platform_guestvisitors.first_seen_at.
     */
    first_seen_at: string & tags.Format<"date-time">;

    /**
     * Most recent observed timestamp for this guest visitor.
     *
     * Prisma: community_platform_guestvisitors.last_seen_at.
     */
    last_seen_at: string & tags.Format<"date-time">;
  };

  /**
   * Authorization response for guest visitors containing JWT token bundle.
   *
   * Returned by guest join and refresh endpoints that operate on the Prisma
   * table community_platform_guestvisitors. The id matches the guest visitor
   * record used for analytics and resumable guarded flows. The token property
   * references the standard IAuthorizationToken type and must never be
   * inlined.
   *
   * Security: This response intentionally excludes potentially sensitive
   * networking or fingerprinting fields (e.g., device_fingerprint,
   * user_agent, ip). Only public-safe summary data may be included alongside
   * the token.
   */
  export type IAuthorized = {
    /** Unique identifier of the authorized guest visitor (UUID). */
    id: string & tags.Format<"uuid">;

    /**
     * First observed timestamp for this guest visitor.
     *
     * Prisma column: community_platform_guestvisitors.first_seen_at
     * (timestamptz).
     */
    first_seen_at?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Most recent observed timestamp for this guest visitor.
     *
     * Prisma column: community_platform_guestvisitors.last_seen_at
     * (timestamptz).
     */
    last_seen_at?: (string & tags.Format<"date-time">) | undefined;

    /** JWT token information for authentication */
    token: IAuthorizationToken;

    /**
     * Optional embedded subject information for convenience.
     *
     * Security: Summary-only; never include sensitive fingerprints or
     * networking hints in authorization responses.
     */
    guestVisitor?: ICommunityPlatformGuestVisitor.ISummary | undefined;
  };
}
