import { ICommunityPlatformCommunityRule } from "./ICommunityPlatformCommunityRule";

/**
 * Array of community rule items.
 *
 * Used by ICommunityPlatformCommunity.rules to include ordered rule snippets
 * for the right sidebar display.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunityRuleArray =
  ICommunityPlatformCommunityRule[];
