/**
 * Sort keys for category listings.
 *
 * These values map to columns in Prisma table community_platform_categories and
 * are safe for public ordering. Providers must apply deterministic tie-breakers
 * when values are equal.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECategorySortBy = "display_order" | "name" | "code" | "created_at";
