/**
 * Voting state for a user's comment vote.
 *
 * Prisma column: community_platform_comment_votes.state. The application uses
 * "Upvote" and "Downvote" as canonical values. The "None" state is represented
 * by absence of an active record (or a record with deleted_at set).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformCommentVoteState = "Upvote" | "Downvote";
