/**
 * Community category enumeration as defined by business requirements.
 *
 * Prisma source: community_platform_communities.category (stored as text). The
 * application enforces selection to one of these allowed values at creation and
 * during updates.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityCategory =
  | "Tech & Programming"
  | "Science"
  | "Movies & TV"
  | "Games"
  | "Sports"
  | "Lifestyle & Wellness"
  | "Study & Education"
  | "Art & Design"
  | "Business & Finance"
  | "News & Current Affairs";
