/**
 * Sort keys for community platform user listings.
 *
 * - CreatedAt → orders by community_platform_users.created_at (desc typically for
 *   Newest)
 * - LastLoginAt → orders by community_platform_users.last_login_at (nulls handled
 *   per provider policy)
 * - Username → orders by community_platform_users.username (collation and
 *   case-insensitive behavior per application rules)
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformUserSortBy =
  | "createdAt"
  | "lastLoginAt"
  | "username";
