/**
 * Allowed sort keys for Community Rule listings.
 *
 * - Order_index: Deterministic display order within a community, unique per
 *   community.
 * - Created_at: Creation timestamp to support Newest ordering.
 * - Updated_at: Last modified timestamp to surface recently edited rules.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformCommunityRuleOrderBy =
  | "order_index"
  | "created_at"
  | "updated_at";
