/**
 * Community sorting mode used across Explore and Search flows.
 *
 * Preferred values:
 *
 * - NameMatch: Rank by case-insensitive Name Match (exact > starts-with > token
 *   containment > fuzzy proximity). Ties resolve by (created_at desc, id
 *   desc).
 * - RecentlyCreated: Order by (created_at desc, id desc) for deterministic
 *   Newest-style listing.
 *
 * For compatibility, case-variant forms may be accepted by some clients;
 * servers should normalize to lower-case.
 *
 * Backed by ordering over Communities.community_platform_communities
 * (created_at, id) or Name Match ranking per business rules.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunitySort =
  | "nameMatch"
  | "recentlyCreated"
  | "NameMatch"
  | "RecentlyCreated";
