/**
 * Allowed columns for ordering community_platform_reserved_terms listings.
 *
 * Matches Prisma columns to support consistent administrative review and
 * validation previews.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformReservedTermOrderBy =
  | "created_at"
  | "term"
  | "term_normalized"
  | "applies_to";
