/**
 * Session listing primary sort keys.
 *
 * Use these values to sort records from Prisma model
 * "community_platform_sessions". Deterministic ordering requires an id
 * (descending) tie‑breaker, and lifecycle filters (revoked_at, expires_at)
 * should be respected according to the UI.
 *
 * Prisma references:
 *
 * - Community_platform_sessions.last_seen_at
 * - Community_platform_sessions.created_at
 * - Community_platform_sessions.expires_at
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformSessionSort =
  | "last_seen_at"
  | "created_at"
  | "expires_at";
