/**
 * Allowed primary sort keys for Registered Member listing requests.
 *
 * - Created_at: order by creation timestamp; tie-break by id desc
 * - Registered_at: order by registered_at; tie-break by id desc
 *
 * Prisma reference: community_platform_registeredmembers.created_at,
 * registered_at.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformRegisteredMemberSort =
  | "created_at"
  | "registered_at";
