/**
 * Order-by fields for recent communities listing.
 *
 * These values map directly to columns in Prisma table
 * community_platform_recent_communities: last_activity_at, created_at, and
 * updated_at. Use together with IESortDirection to build deterministic
 * sorting.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformRecentCommunityOrderBy =
  | "last_activity_at"
  | "created_at"
  | "updated_at";
