/**
 * Lifecycle status filter for sessions.
 *
 * These values map to lifecycle columns in Prisma model
 * "community_platform_sessions":
 *
 * - Active: revoked_at is null and expires_at is in the future
 * - Revoked: revoked_at is not null
 * - Expired: expires_at is in the past
 * - All: include all lifecycle states
 *
 * Prisma references:
 *
 * - Community_platform_sessions.revoked_at
 * - Community_platform_sessions.expires_at
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformSessionStatus =
  | "active"
  | "revoked"
  | "expired"
  | "all";
