/**
 * Sorting options for comments.
 *
 * Per business and search requirements, comments support the canonical Newest
 * ordering only (created_at descending; ties by larger identifier). This enum
 * constrains the allowed sort option to a single value for deterministic
 * behavior.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformCommentSort = "Newest";
