/**
 * Allowed community categories (application-level enumeration).
 *
 * Prisma mapping: Communities.community_platform_communities.category (text).
 * The application enforces exactly one selection from this fixed set at
 * creation/update time. Values are human-readable per business specification.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformCommunityCategory =
  | "Tech & Programming"
  | "Science"
  | "Movies & TV"
  | "Games"
  | "Sports"
  | "Lifestyle & Wellness"
  | "Study & Education"
  | "Art & Design"
  | "Business & Finance"
  | "News & Current Affairs";
