/**
 * Site Admin assignment primary sort keys.
 *
 * Use these values to sort records from Prisma model
 * "community_platform_siteadmins". Apply deterministic ordering by breaking
 * ties with id (descending) after the chosen primary key.
 *
 * Prisma references:
 *
 * - Community_platform_siteadmins.granted_at
 * - Community_platform_siteadmins.created_at
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformSiteAdminSort = "granted_at" | "created_at";
