/**
 * Vote state enumeration used across posts and comments.
 *
 * Business semantics per Voting requirements: UPVOTE contributes +1, DOWNVOTE
 * contributes −1, and NONE represents no effective vote (typically absence of a
 * row in the corresponding vote table).
 *
 * This is a presentation-level enum; persistence of vote states is modeled via
 * Prisma tables community_platform_post_votes and
 * community_platform_comment_votes with value ∈ {1, -1}.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformVoteState = "UPVOTE" | "DOWNVOTE" | "NONE";
