/**
 * Ordering fields for application settings listings.
 *
 * Matches Prisma columns community_platform_app_settings.key, .created_at, and
 * .updated_at. Use to control list sorting deterministically.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IECommunityPlatformAppSettingOrderBy =
  | "key"
  | "created_at"
  | "updated_at";
