/**
 * Sort direction enumeration.
 *
 * - Asc: ascending order
 * - Desc: descending order
 *
 * Used by many IRequest DTOs across listing/search endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEOrderDirection = "asc" | "desc";
