/**
 * Post sort modes supported across feeds and search.
 *
 * - Newest: Order by community_platform_posts.created_at DESC; tie-break by id
 *   DESC.
 * - Top: Order by aggregated score (sum of community_platform_post_votes.value
 *   where deleted_at is null) DESC; tie-break by created_at DESC, then id
 *   DESC.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEPostSort = "newest" | "top";
