/**
 * Ordering keys for listing post snapshots.
 *
 * - Created_at: order by snapshot creation timestamp (default)
 * - Id: deterministic ordering by identifier
 * - Title: alphabetical ordering by recorded title
 *
 * Used by ICommunityPlatformPostSnapshot.IRequest.orderBy.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEPostSnapshotOrderBy = "created_at" | "id" | "title";
