/**
 * Post vote state enumeration.
 *
 * This enum captures canonical voting values for Prisma model
 * community_platform_post_votes.state. The application standardizes lower-case
 * values aligned with comment votes for cross-domain consistency.
 *
 * Values:
 *
 * - "up": Upvote selection by the current user
 * - "down": Downvote selection by the current user
 *
 * Business context: The "None" state is represented by absence of an active
 * vote record (or an inactive record with deleted_at set) and is effected via
 * the DELETE vote endpoint. Scores are computed as upvotes minus downvotes
 * across active records.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEPostVoteState = "up" | "down";
