/**
 * Sort fields supported by ICommunityPlatformRecentCommunity.IRequest.
 *
 * Values correspond to Prisma columns in community_platform_recent_communities:
 * last_activity_at, created_at, and updated_at.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IERecentCommunityOrderBy =
  | "last_activity_at"
  | "created_at"
  | "updated_at";
