/**
 * Sorting direction indicator.
 *
 * Use "asc" for ascending order and "desc" for descending order across list
 * endpoints that support sorting.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IESortDirection = "asc" | "desc";
