/**
 * Sortable fields for user restriction searches, mapped from Prisma timestamps.
 *
 * - CreatedAt → community_platform_guestvisitors.created_at
 * - AssignedAt → community_platform_guestvisitors.assigned_at
 * - RestrictedUntil → community_platform_guestvisitors.restricted_until
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEUserRestrictionSortBy =
  | "createdAt"
  | "assignedAt"
  | "restrictedUntil";
