/**
 * Vote direction enumeration used by update operations that require an explicit
 * choice between an Upvote or a Downvote.
 *
 * This enum maps to the domain of values persisted in Prisma voting tables
 * where value ∈ {-1, 1}. Specifically, community_platform_post_votes.value and
 * community_platform_comment_votes.value store directional intent: 1 for upvote
 * and -1 for downvote. Transition to a neutral state (None) is represented by
 * deleting the corresponding vote row rather than storing 0.
 *
 * Business rules: Clients use this enum only in write requests (PUT) to set a
 * concrete direction. Clearing a vote (switching to None) is handled by DELETE
 * endpoints which remove the vote row.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEVoteDirection = "UPVOTE" | "DOWNVOTE";
