/**
 * Enumeration of effective per-user vote states for content.
 *
 * Business mapping: values derive from the presence and value of a row in
 * community_platform_post_votes or community_platform_comment_votes for the
 * authenticated user (value ∈ {1, −1}); the NONE state corresponds to no row
 * (or a deleted row) and is not persisted. Used by list/detail DTOs to present
 * personalized vote UX without exposing raw identifiers.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEVoteState = "UPVOTE" | "DOWNVOTE" | "NONE";
