import { IPage } from "./IPage";
import { ICommunityPlatformSession } from "./ICommunityPlatformSession";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformSession = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ICommunityPlatformSession[];
};
export namespace IPageICommunityPlatformSession {
  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type ISummary = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: ICommunityPlatformSession.ISummary[];
  };
}
