import { IPage } from "./IPage";
import { I } from "./I";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageI = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: I[];
};
export namespace IPageI {
  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type IPagination = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: I.IPagination[];
  };

  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type IRequest = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: I.IRequest[];
  };
}
