/**
 * Vote state enumeration used across voting outcomes.
 *
 * This enum represents the caller’s effective vote on a content item after an
 * operation. Values:
 *
 * - NONE: No active vote exists (absence of a vote row in Prisma tables).
 * - UPVOTE: An upvote is applied (value = 1 in vote tables).
 * - DOWNVOTE: A downvote is applied (value = -1 in vote tables).
 *
 * Backed by Prisma vote models: Posts.community_platform_post_votes and
 * Comments.community_platform_comment_votes where deleted_at is null for
 * tallies.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVoteState = "NONE" | "UPVOTE" | "DOWNVOTE";
